### ISSUE TITLE
Live draft

### ISSUE THREAD

**Issue by Darrend1** [rbrnk/fflproject#10]
Pretty much got everything working except having an issue where draft information is not updated unless everyone refreshes the page after someone picks. Any ideas or suggestions?

**Comment by nickfrerichs** [comment]
Are you running IIS or Apache?

**Comment by Darrend1** [comment]
apache

**Comment by nickfrerichs** [comment]
Hmm, after you've logged in, try browsing here:
http://<yourdomain>/season/draft/stream_get_update_key,
you should get a stream of data repeating similar to this:

data: 0-1470699441

data: 0-1470699441

data: 0-1470699441

data: 0-1470699441

data: 0-1470699441

data: 0-1470699441

data: 0-1470699441

data: 0-1470699441

data: 0-1470699441

**Comment by Darrend1** [comment]
Just a page that never loads. Nothing displayed

**Comment by nickfrerichs** [comment]
The live chat functions in the same way as the draft.  When you click the
Chat button are you able to interactively chat?  If not, check your
browser's javascript console to see if there are errors.

Also, what web browser are you using?

**Comment by Darrend1** [comment]
submitting a chat message does make its way to the db, and also makes a toast (or whatever notification) in the top menu bar.  However, clicking the chat button will pop up the chat window, but will constantly show a loading message. Tried Chrome and IE. Only debugging info I get in any browser is that it is pending. No failure messages, just pending.

**Comment by nickfrerichs** [comment]
When Bob has issues with this it turned out to be a buffering setting that needed to be change on IIS.  Would you be able to post a url to your php config?  If you create a new .php file somewhere and put <?php phpinfo(); ?> in the contents.

**Comment by Darrend1** [comment]
I'm not live on the net yet, but navigate to http://deltatini.com/ and I pasted the php info results

**Comment by nickfrerichs** [comment]
Thanks, I'll take a look.

Another thing to check.

Uncomment the two lines of code for the `$count` variable in: `application/controllers/league/Chat.php` in `function stream_get_chat_key()`

Then change `while(1)` to `while($count > 0)`

Then browse to http://<yourdomain>/league/chat/stream_get_chat_key
Within 5-10 seconds see if it returns output similar to:

data: 4

data: 4

data: 4

If so, it has something to do with buffering not flushing.

**Comment by Darrend1** [comment]
Got some data:
data: 3
data: 3
data: 3
data: 3
data: 3
data: 3
data: 3
data: 3
data: 3
data: 3

Actually seems to be working now. Nice! Gotta test the draft out and I'll report back

**Comment by Darrend1** [comment]
Changed the while(1) to while($count > 0) in application\controllers\season\draft.php and now draft seems to be working correctly also.

Thanks for the help Nick

**Comment by nickfrerichs** [comment]
While I think it probably makes it work, it's only cause the event stream connection is restarting every 5 seconds.  So your updates will happen every 5s instead of .5s.

I'm pretty sure it's a buffering issue and have a feeling it's cause I wrote my code for PHP 5.4 and you're running 5.6.  I'll try to figure out what's up.

**Comment by Darrend1** [comment]
Setting usleep to 500 seems like it gets closer to that .5 second mark. Will that have negative affects elsewhere?

**Comment by nickfrerichs** [comment]
It's just inefficient cause you're tearing down and creating a new
connection every 500ms in order to retrieve a very tiny piece of heartbeat
data.  Multiply this by the number or users connected and it could bog down
your server.

It's much better to keep a single connection to the server open that
trickles the heartbeat in an infinite loop, which is how it's supposed to
work.

I'll try to recreate it on a php 5.6 install and get back to you.

**Comment by nickfrerichs** [comment]
Well I think I've found the reason it's not working, but I don't know of a solution.

The difference between our configurations is that you are using FPM/FastCGI and I am not  (Interestingly, the similar issue with IIS also involves FastCGI).  I found a reference to the same issue here: http://stackoverflow.com/questions/30707792/how-to-disable-buffering-with-apache2-and-mod-proxy-fcgi.  Assuming you're using mod_proxy_fcgi, doesn't sound like there's a good fix.

Essentially, though my code tells PHP to flush the buffer for each heartbeat, FastCGI has a buffer of it's own so the data is not sent until that buffer is full, and since it's a trickle of data your web browser has to wait a long time.

I'd recommend not using FPM/FastCGI if you can.  I may look at moving to websockets for next year, but I'm not familiar enough to know of disadvantages.

The change you made earlier may appear to work, but I'm surprised it does and it could cause other issues.  If you continue to go that route, I'd remove the while loop altogether and use usleep(2000000), since it's actually in micro seconds, so that means it would update every 2 seconds.

**Comment by Darrend1** [comment]
Thanks for the info and for researching the issue. I will make the changes and attempt to look into the issue more with the information you provided. Either way, i like the way the new site runs. We can live with a little bit of a delay during the draft. Thanks again for all the work you have put into the project.
