### ISSUE TITLE
Injury Icon

### ISSUE THREAD

**Issue by Boblyng** [rbrnk/fflproject#16]
This isn't an actual issue but still looking for something that we could use to mark injured players. That was one of the biggest things we had problems with.
I have my site updated to latest development version looking good.

**Comment by nickfrerichs** [comment]
Bob,

I've not found any free source for player injury data, but I may be able to pull "news" for players using the nfl fantasy api (http://api.fantasy.nfl.com/v1/docs/service?serviceName=playersNews).  Do you think that might be of use?  I could possibly parse the content for words related to player injuries.

**Comment by Darrend1** [comment]
I have a script we used in our league that worked good on the lineup submit page. If I have time when I get home i'll see if I can post it here.

**Comment by Boblyng** [comment]
Lets see what Darrend1 has otherwise if the injury news from the api could be parsed so it pops the injury note or icon next to the player in the main team view at least that would be good.

**Comment by Boblyng** [comment]
How confident are you in the nflgame stats vs the api stats going forward?

**Comment by Darrend1** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20862091/26232285/02437ab6-3c0a-11e7-9f11-6dd17e49bda0.png)

Ill edit this with the code later when I get to my server. But essentially it pulls the injury list from rotowire and throws it into a injury table in the database. I currently have the script run a few times a week to pull injuries. Then when the user loads a page, such as the lineup submit page, it pulls the injury data from there while pulling the starting lineups. I have it set to show additional injury info when you mouse over the player. Our site has a lot of custom stuff, so I'm gonna have to cross reference the default files to see what's actually changed. It's not much code to add though, I know that.

I used rotowire due to the details and up to date injury statuses.

**Comment by nickfrerichs** [comment]
I try to avoid depending on web scraping, do you have a way to get a feed and match up player IDs with rotowire?

I can probably add a table for player history/news that displays on the site and leave it up to you to have a script populate it with data.

As far as nflgame vs the nfl.com fantasy api.  When I looked at the fantasy api last year it was not nearly as live as nflgame.  That api is intended to write your own interface to manage a nfl.com fantasy league rather than provide stats.  So I'll be sticking with nflgame because of the near real-time stats for live scoring.

**Comment by Boblyng** [comment]
I was trying to parse the nfl news api into the database using.
`<?php
url = "http://api.fantasy.nfl.com/v1/players/news";
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_URL, $url); //gets the url contents

$data = curl_exec ($ch); // Execute Curl request
curl_close($ch);

$xml = simplexml_load_string($data);
$con=mysql_connect("localhost","root","XXXXXX");
mysql_select_db("ffl_project", $con) or die mysql_error()); //Select Database

foreach ($xml -> note as $row) {
	$gsisPlayerId= = $row -> gsisPlayerId;
	$body = $row -> body;
	$analysis = $row -> analysis;
	
//perform sql query
$sql = "INSERT INTO `injury_table` (`gsisPlayerId`, `body`,`analysis`)"	
			. "VALUES ('$gsisPlayerId', '$body', '$analysis')";
			
$result = mysql_query ($sql);
if  (!$result)	{
	echo 'MYSQL ERROR';
    } else {
		 echo 'SUCCESS';
	 }
}		
?>`
But the gsisPlayerId seems to be giving me error.
Here is an example row.

`<note id="342839" esbid="GOL705804" gsisPlayerId="00-0024410" firstName="Kedric" lastName="Golston" position="DL" teamAbbr="" source="rotowire" timestamp="2017-05-21 14:21:45"><headline/><body>Golston (hamstring) visited with the 49ers on Friday, Matt Barrows of The Sacramento Bee reports.</body><analysis>Golston, who opened the 2016 season as the Redskins' starting nose tackle but suffered a season-ending hamstring tear in Week 2, was medically cleared from the injury roughly two and a half weeks ago. This meeting with San Francisco marks the first free-agent visit of the offseason for the 33-year-old vet. The 49ers are beginning to construct a fearsome defensive line and Golston would, at the minimum, provide excellent depth and a strong veteran presence.</analysis></note>`

**Comment by Boblyng** [comment]
Otherwise I was looking at it in json format.
http://api.fantasy.nfl.com/v1/players/news?format=json

**Comment by nickfrerichs** [comment]
Bob,

Don't worry, I'll have a new argument for update.py to read in the player
news from that api and make it available in the gui.  It's only web
scraping and matching of first/last names to gather the data that I'll
leave up to you if you want to go that route.

Nick

**Comment by nickfrerichs** [comment]
I'm going to close this, a basic icon is in develop now and it pulls from nfl.com/injuries.  Once I know it's reliable, I'll refine the look over the season.  Currently it looks too much like a Cherrio
