### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#19]
Hi - I've attempted to get the project running - but right now I can only get an error message on step 1 - 
"Your config file does not appear to be formatted correctly."

I have placed the fflproject directory in my /var/www/http directory.
I copied the config-example.php to /fflproject/application/config/config.php and modified as below:

This is my config.php file:
<?php
$fflp_baseurl = '';
$fflp_dbhost = 'localhost';
$fflp_dbname = 'mynewdatabase';
$fflp_dbuser = 'mydbuser';
$fflp_dbpass = 'password';
$fflp_salt = '';
// Set these if you want to use Google's reCAPTCHA
$fflp_use_recaptcha = False;
$fflp_recaptcha_public_key = '';
$fflp_recaptcha_private_key = '';
$fflp_email_site_title = '';
$fflp_email_reply_to = '';
$fflp_smtp_host = 'ssl://smtp.gmail.com';
$fflp_smtp_user = '';
$fflp_smtp_pass = '';
$fflp_smtp_port = 465;
// Set this to smtp to use these settings, or sendmail to ue your local settings
$fflp_smtp_protocol = "smtp";
// Set this to "\r\n" "\r" or "\n", can cause auth issues if not correct for your OS.
$fflp_smtp_newline = "\r\n";
// Show debug and profiler data
$fflp_debug = True;
$fflp_log_threshold = 0;
// Log user out (expire session) after this many seconds of of inactivity (1 week default)
$fflp_session_expire = 60*60*24*7;

I've double checked the database - connection details work to connect - I don't know where to look for the issue - any suggestions would be greatly appreciated!

**Comment by nickfrerichs** [comment]
You'll want to copy config-example.php to /var/www/http/config.php, your site root.  FFLProject has a config file there since actual configuration is stored in multiple places, this way it can all be changed in one spot.  If you copy it to ./application/config/config.php, you have overwritten the CodeIgniter config file, which is why you're seeing the CI error.

I added that clarification here: https://github.com/nickfrerichs/fflproject/wiki/1:-Setup-front-end
