### ISSUE TITLE
Roster - bench positions not preserved week to week

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#40]
Noticed that the "roster" table does not contain any means to know when a player was acquired or released, so when looking at history cannot calculate "bench" score by week.  Maybe we add two columns to roster table - week added and week removed, so you can see historically what the bench was in prior weeks?

**Comment by nickfrerichs** [comment]
Yeah, this is something Bob has brought up. In the past in my league we were able to add/remove players all weekend long so long as the players' games haven't begun yet, which results in a real fluid bench and it's difficult to say who exactly was on your bench that weekend as it can change at any minute.

But, it should be easy enough to add a table similar to "starter" but called "bench" and have it updated anytime you start/sit/drop players to provide for the weekly historic data you're after.

At minimum I'll get the table added and make sure the data is being tracked during the off season. Secondary will be the cosmetics of displaying the new data.. also isn't too hard, but since I tend to work on cosmetic things during the season, it may slide until then... just depends.

**Comment by nickfrerichs** [comment]
This has been added in the latest version, there is a new bench table and logic was added site wide to keep it up to date as players are added/dropped, started/sited, traded, etc.

Nothing has been added cosmetically yet to show bench score by week, but the code is there to collect the data at the start of the 2018 season. I'll work on the cosmetic part once the season starts.
