### ISSUE TITLE
Chat/Draft issue again

### ISSUE THREAD

**Issue by Darrend1** [rbrnk/fflproject#41]
I'm having an issue again this year. The page is not refreshing chat/draft data.  I can navigate to http:///sse/stream and I echo'd the count so I can see it updating every half second. I can also immediately see when messages are posted. The actual page though doesn't register the change. I know it may have had something to do with FPM previously, but I got it working by changing while(1) to while($count > 0) but since its now while($count > 0) by default, i'm not sure where to look or if its possible. Doesn't need to be efficient, just needs to work (mainly for draft) :)

Update:
Funny part is the draft will work but responds very slowly. Actions such as starting the draft etc take 30 seconds. Picks are much quicker. Chats update as picks are made/etc but not otherwise.

**Comment by nickfrerichs** [comment]
While the live draft is in progress and at the live draft page.... Turn on debugging, then open up a javascript console in developer mode (https://developer.chrome.com/devtools). Do you see live_draft data arriving every 5 seconds? (Data gets pushed whenever an action happens, the 5s updates are to make sure things stays in sync since timing is important).

What server are you running? LInux/Windows Apache/IIS?
What browser are you using to test?  Does it act the same in all browsers you've tried?

**Comment by Boblyng** [comment]
I had this issue using windows server 2008. I wasn't ever really able to speed it up so I switched to Debian8 Linux last year and the difference is like night and day.

**Comment by Darrend1** [comment]
I get 5 of these bunched together every 30 or so seconds -
```
SSE Stream data                                    fflproject.js:780
{ls: "off", wo: Array(1), ur: "0"}                fflproject.js:781 
```

Linux, Apache 2.4, Php5.6. Tried different browsers with same result. 

It looks like sending commands/chats etc immediately shows up in the console but the actual pages take 30+ seconds to update what was done. (manual page refresh immediately shows the new data)

**Comment by nickfrerichs** [comment]
Darrend1,

While a live draft is in progress, what happens when you browse to <your domain>/sse/stream/sse_live_draft ? Do you only see updates every 30 seconds as well or do you get the 5s updates?  You can only make ~5 connections to the site in one browser, so make sure all other browser windows are closed for testing.

**Comment by Darrend1** [comment]
Ok, (**"live_draft":{"seconds_left")** messages are about 20 seconds apart and come in bunches of 4 or 5.
Chat messages are about 210 seconds from submission to them actually showing up in chat.

**Comment by nickfrerichs** [comment]
Darrend1,

When is your draft? I'll probably have to set up an identical system to yours to see if I can recreate the issue, but I'm not sure I'll get to it real soon.

What Linux OS are you running Apache/php on?

**Comment by nickfrerichs** [comment]
Darrend, is this still a problem for you? If not, I'm going to close this one.
