### ISSUE TITLE
player points show 0 when viewing "League -> Players"

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#51]
The table of players shows 0 for points for all players, however clicking on player will show proper points:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/18621147/45259718-e69d2e00-b3a0-11e8-90b6-64dfa7ea0d8e.png">

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/18621147/45259730-0e8c9180-b3a1-11e8-920c-561e512d77c2.png">

After running update.py -stats_summary the points is populated.  Is there harm to running this all the time to keep display updated?

**Comment by Boblyng** [comment]
Yep I have the same issue.

**Comment by nickfrerichs** [comment]
This is because the summary stats haven't been calculated yet. So from the python directory run "python update.py -stats_summary"

This calculates player totals and stores them in a summary table which all of the multi-week statistics pages use.

You could probably schedule it to run as often as you'd like. Think of it as a backend process that collects permanent stats as games complete.
