### ISSUE TITLE
Anyone missing Jacksonville players?

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#54]
Has anyone noticed that for Jacksonville players the team is not set properly?  It seems all of my Jacksonville players have 0 as the nfl_team_id - has anyone else had this?

**Comment by Boblyng** [comment]
I haven't seen that issue since last year. A couple things to check first are in the nfl_teams table do you have the abbreviation as JAX? And in the __init__.py file in the nflgame folder do you have is listed as JAX? If Yes then you will most likely need to need to manually update the players table for your Jacksonville players changing the nfl_team_id from 0 to 15.

**Comment by bubbajones69** [comment]
looks like it was a carry over from last year - rebuilt database sorted it out
